import Head from "next/head";
import Image from "next/image";
import ConnectWallet from "../components/ConnectWallet";
import ContractCallVote from "../components/ContractCallVote";
import ContractCallSendMsg from "../components/ContractCallSendMsg";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Post a Message 👋</h1>

        <div className={styles.components}>
          {/* ConnectWallet file: `../components/ConnectWallet.js` */}
          <ConnectWallet />
          <ContractCallSendMsg />
        </div>

      </main>

      <footer className={styles.footer}>
        Done by LΩ
      </footer>
    </div>
  );
}
